# Generated by Django 3.1.3 on 2020-11-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20201124_1927'),
        ('daragat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daragat',
            name='clas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.classstudent', verbose_name='اسم الفصل'),
            preserve_default=False,
        ),
    ]
