# Generated by Django 3.1.3 on 2020-11-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daragat', '0002_daragat_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daragat',
            name='athkar',
            field=models.IntegerField(default=20, verbose_name='درجة مادة الاذكار'),
        ),
    ]
