# Generated by Django 3.1.3 on 2020-11-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daragat', '0002_remove_daragat_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daragat',
            name='name_name',
        ),
    ]
