# Generated by Django 3.1.3 on 2020-11-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daragat', '0003_remove_daragat_name_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='daragat',
            name='kind',
            field=models.CharField(choices=[('شهادة نصف العام', 'شهادة نصف العام'), ('شهادة نهاية العام', 'شهادة نهاية العام')], default='', max_length=50, verbose_name='نوع الهادة'),
            preserve_default=False,
        ),
    ]
