# Generated by Django 3.1.3 on 2020-11-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daragat', '0003_auto_20201124_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daragat',
            old_name='name',
            new_name='name_name',
        ),
    ]
