# Generated by Django 3.1.3 on 2020-11-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201130_1811'),
        ('daragat', '0004_daragat_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='daragat',
            name='name_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='الاسم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daragat',
            name='kind',
            field=models.CharField(choices=[('شهادة نصف العام', 'شهادة نصف العام'), ('شهادة نهاية العام', 'شهادة نهاية العام')], max_length=50, null=True, verbose_name='نوع الهادة'),
        ),
    ]
