# Generated by Django 3.1.3 on 2020-11-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buses',
        ),
    ]
