# Generated by Django 3.1.2 on 2020-11-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default='noimg.png', upload_to='studentsimg/'),
        ),
    ]
