# Generated by Django 3.1.3 on 2020-11-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_delete_buses'),
    ]

    operations = [
        migrations.CreateModel(
            name='hafela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nem', models.CharField(max_length=50, verbose_name='اسم السائق')),
                ('bus_id', models.CharField(max_length=50, verbose_name='رقم الحافلة')),
                ('bus_price', models.IntegerField(verbose_name='السعر الشهري')),
            ],
        ),
    ]
