# Generated by Django 3.1.3 on 2020-11-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_hafela'),
    ]

    operations = [
        migrations.AddField(
            model_name='hafela',
            name='bus_student',
            field=models.ManyToManyField(to='student.Student', verbose_name='اطفال الحافلة'),
        ),
    ]
