# Generated by Django 3.1.2 on 2020-11-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201103_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_masrof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم التصنيف')),
            ],
        ),
        migrations.CreateModel(
            name='masrofat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_masrofat', models.CharField(max_length=95, verbose_name='وصف المستلزم')),
                ('price_masrofat', models.IntegerField(verbose_name='سعر المستلزم')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.category_masrof', verbose_name='التصنيف')),
            ],
        ),
    ]
