# Generated by Django 3.1.2 on 2020-11-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_category_masrof_masrofat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount_paid',
            field=models.IntegerField(),
        ),
    ]
