# Generated by Django 3.1.3 on 2020-11-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_hafela_bus_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='الاسم'),
        ),
    ]
