# Generated by Django 3.1.3 on 2020-11-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20201105_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم السائق')),
                ('id_id', models.CharField(max_length=50, verbose_name='رقم الاتوبس')),
                ('salary', models.IntegerField(verbose_name='السعر الشهري')),
            ],
        ),
        migrations.CreateModel(
            name='mawad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classstudent', verbose_name='الفصل')),
            ],
        ),
    ]
