# Generated by Django 3.1.3 on 2020-12-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201130_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hafela',
            old_name='nem',
            new_name='nam',
        ),
    ]
