# Generated by Django 3.1.3 on 2020-11-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_buses_mawad'),
    ]

    operations = [
        migrations.CreateModel(
            name='khaeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('Excuse', models.BooleanField(default=True, verbose_name='بعذر ام لا')),
                ('Reason', models.TextField()),
                ('name_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classstudent', verbose_name='اسم الحلقة')),
                ('name_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='')),
            ],
        ),
    ]
