# Generated by Django 3.1.3 on 2020-12-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20201201_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.hafela', verbose_name='الحافلة'),
        ),
    ]
