# Generated by Django 3.1.3 on 2020-11-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_khaeb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='khaeb',
            new_name='Absence',
        ),
    ]
