# Generated by Django 3.1.3 on 2020-12-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.hafela', verbose_name='الحافلة'),
        ),
        migrations.CreateModel(
            name='rateb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuor_rateb', models.IntegerField(verbose_name='الراتب')),
                ('name_techer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.classstudent', verbose_name='اسم المعلمة')),
            ],
        ),
    ]
