# Generated by Django 3.1.3 on 2020-11-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20201119_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='Reason',
            field=models.TextField(null=True, verbose_name='العذر'),
        ),
    ]
