# Generated by Django 3.1.3 on 2020-12-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20201202_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rateb',
            options={'verbose_name': 'الرواتب', 'verbose_name_plural': 'الرواتب'},
        ),
        migrations.AddField(
            model_name='student',
            name='numer',
            field=models.IntegerField(default=0, verbose_name='الرقم القومي'),
        ),
    ]
