# Generated by Django 3.1.3 on 2020-12-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20201203_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='numer',
            field=models.TextField(default=0, max_length=100, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_father',
            field=models.TextField(max_length=100, verbose_name='رقم هاتف الوالد'),
        ),
    ]
